# Generated by Django 4.2.16 on 2025-09-25 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Configuración',
                'verbose_name_plural': 'Logs de Configuración',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa', max_length=200)),
                ('rut_empresa', models.CharField(blank=True, max_length=20)),
                ('direccion_empresa', models.TextField(blank=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=20)),
                ('email_empresa', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('moneda_principal', models.CharField(default='CLP', max_length=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('formato_factura', models.CharField(default='FAC-{numero}', max_length=50)),
                ('zona_horaria', models.CharField(default='America/Santiago', max_length=50)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('formato_fecha', models.CharField(default='%d/%m/%Y', max_length=20)),
                ('email_notificaciones', models.BooleanField(default=True)),
                ('smtp_servidor', models.CharField(blank=True, max_length=100)),
                ('smtp_puerto', models.IntegerField(default=587)),
                ('smtp_usuario', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_tls', models.BooleanField(default=True)),
                ('respaldo_automatico', models.BooleanField(default=False)),
                ('frecuencia_respaldo', models.CharField(default='semanal', max_length=20)),
                ('ruta_respaldos', models.CharField(blank=True, max_length=500)),
                ('sesion_timeout', models.IntegerField(default=30)),
                ('intentos_login_max', models.IntegerField(default=5)),
                ('bloqueo_tiempo', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('tecnicos', 'Técnicos'), ('productos', 'Productos'), ('cotizaciones', 'Cotizaciones'), ('reportes', 'Reportes'), ('dashboard', 'Dashboard')], max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_dato', models.CharField(default='string', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Módulo',
                'verbose_name_plural': 'Configuraciones de Módulos',
                'unique_together': {('modulo', 'clave')},
            },
        ),
    ]
