# Generated by Django 4.2.16 on 2025-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='afp',
            field=models.CharField(choices=[('afp_capital', 'AFP Capital'), ('afp_provida', 'AFP Provida'), ('afp_habitat', 'AFP Habitat'), ('afp_planvital', 'AFP PlanVital'), ('afp_cuprum', 'AFP Cuprum'), ('afp_modelo', 'AFP Modelo')], default='afp_capital', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='departamento',
            field=models.CharField(choices=[('operaciones', 'Operaciones'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración'), ('ventas', 'Ventas'), ('soporte', 'Soporte Técnico')], default='operaciones', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nombre_emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='postre_favorito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='prevision',
            field=models.CharField(choices=[('fonasa', 'FONASA'), ('isapre_banmedica', 'Isapre Banmédica'), ('isapre_colmena', 'Isapre Colmena'), ('isapre_consalud', 'Isapre Consalud'), ('isapre_cruz_blanca', 'Isapre Cruz Blanca'), ('isapre_vida_tres', 'Isapre Vida Tres')], default='fonasa', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='puesto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ubicacion',
            field=models.CharField(choices=[('santiago', 'Santiago'), ('valparaiso', 'Valparaíso'), ('concepcion', 'Concepción'), ('antofagasta', 'Antofagasta'), ('temuco', 'Temuco'), ('iquique', 'Iquique')], default='santiago', max_length=20),
        ),
    ]
